export class DialogSystem {
    constructor(npcManager) {
        this.npcManager = npcManager;
        this.currentNPC = null;
        this.dialogBox = document.getElementById('dialog-box');
        this.npcNameEl = document.getElementById('npc-name');
        this.dialogTextEl = document.getElementById('dialog-text');
        this.synth = window.speechSynthesis;

        this.dialogs = this.generateDialogs();
    }

    generateDialogs() {
        return {
            'Cogsworth': [
                "Ah, greetings traveler! Welcome to our industrious city of brass and steam.",
                "The great clocktower keeps perfect time, down to the millisecond. A marvel of engineering!",
                "I've been maintaining these mechanisms for forty years. Each gear tells a story.",
                "Did you know the city runs entirely on steam pressure? Ingenious system!",
                "The factories never sleep. Progress marches on, day and night.",
                "I once met the inventor who designed the pressure regulators. Brilliant mind!",
                "These goggles? Essential for working with hot steam and flying sparks.",
                "The brass fittings are imported from the eastern foundries. Finest quality!",
                "Every morning I adjust the pressure valves. Keeps everything running smooth.",
                "My grandfather worked on the original steam engines. It's in my blood.",
                "The hiss of steam is like music to my ears after all these years.",
                "See that gauge? It monitors the entire city's pressure network.",
                "I've got calluses from turning wrenches, but I wouldn't trade this life.",
                "The pneumatic mail system delivers letters in under three minutes!",
                "Young folk today don't appreciate the elegance of mechanical engineering.",
                "This pocket watch was crafted by the finest horologist in the realm.",
                "The steam whistles mark shift changes. Six times a day, like clockwork.",
                "I could teach you to read pressure gauges, if you have a few hours.",
                "The copper piping needs constant polishing or it tarnishes something fierce.",
                "At night, the glow from the furnaces lights up the whole city.",
                "I remember when they first installed the central boiler. What a day!",
                "The engineering guild meets every Thursday to discuss innovations.",
                "My wrench collection numbers over two hundred different sizes and styles.",
                "Steam power will revolutionize the world, mark my words!",
                "Safe travels, friend. Keep your pressure steady and your gears well-oiled!"
            ],
            'Gearhart': [
                "Good day! I'm Gearhart, master of metallurgy and alloy crafting.",
                "The secret to strong brass is the precise copper-to-zinc ratio.",
                "I've developed seventeen new alloys for high-pressure applications.",
                "Steel must be tempered at exactly the right temperature. No room for error!",
                "The furnaces reach temperatures that would melt common metals instantly.",
                "I'm working on a new corrosion-resistant coating for steam pipes.",
                "Every metal has its own personality, its own way of behaving under stress.",
                "The sound of hammering on anvils is the heartbeat of progress.",
                "I once forged a gear so precise it had tolerances of a thousandth of an inch.",
                "Bronze is making a comeback for decorative fittings. Beautiful patina!",
                "The carbon content in steel determines its hardness and flexibility.",
                "I apprenticed for twelve years before I was allowed to work solo.",
                "The guild seal on my work guarantees quality for fifty years.",
                "Molten metal is dangerous but mesmerizing. Like liquid sunlight!",
                "I supply components to half the factories in the industrial district.",
                "The art of casting requires patience and precise temperature control.",
                "I've got burns and scars, each one from a lesson learned.",
                "The new chromium plating technique gives such a lustrous finish!",
                "Iron ore quality has been declining. I have to source from farther away now.",
                "My grandfather's anvil still sees daily use. Built to last centuries!",
                "The relationship between heat treatment and metal properties fascinates me.",
                "I'm mentoring three apprentices currently. The future of the trade!",
                "Custom orders are my specialty. If you can dream it, I can forge it.",
                "The metallurgical library contains texts dating back three hundred years.",
                "May your path be as strong as tempered steel, friend!"
            ],
            'Steamwhistle': [
                "Steamwhistle's the name, locomotive engineering's the game!",
                "I've designed rail systems that span hundreds of miles across rough terrain.",
                "The new express engine can hit sixty miles per hour on straightaways!",
                "Steam locomotion is the future of transportation, no doubt about it.",
                "I've crossed deserts and mountains, all powered by steam and determination.",
                "The rhythmic chug of pistons is the most beautiful sound in the world.",
                "Rail networks connect our civilization. We're building the future!",
                "I once outran a sandstorm in my prototype high-speed engine.",
                "The engineering tolerances on drive wheels are absolutely critical.",
                "Coal quality affects everything - speed, efficiency, maintenance intervals.",
                "I've mapped out routes that cut travel time by forty percent.",
                "The whistle codes communicate between trains. It's a whole language!",
                "My crew can swap out a boiler in under six hours. We're that good!",
                "The newest safety valves have reduced accidents by seventy percent.",
                "I dream in blueprints and wake up solving mechanical problems.",
                "The transcontinental line will be my greatest achievement when it's done.",
                "Every grade and curve has to be calculated precisely for safety.",
                "I've trained over a hundred engineers and conductors in my career.",
                "The golden spike ceremony when we connect two rail lines - gives me chills!",
                "Steam pressure management is what separates great engineers from good ones.",
                "I carry a scale model of my first engine design. For good luck!",
                "The sound of steel wheels on steel rails sings of progress and connection.",
                "Navigation by steam and steel - it's poetry in motion!",
                "I'm working on plans for an underground rail system. Revolutionary!",
                "Keep your boiler hot and your track clear, traveler!"
            ],
            'Brasswick': [
                "Brasswick at your service! Finest brassworks in three counties!",
                "I specialize in ornamental brass fixtures with functional beauty.",
                "The art nouveau style is perfect for steampunk aesthetics, don't you think?",
                "Polishing brass to a mirror shine takes patience and the right compounds.",
                "I've decorated mansions, town halls, and even a royal palace!",
                "Every scroll and flourish is hand-crafted. No two pieces identical.",
                "The green patina on aged brass tells the story of time and weather.",
                "I combine traditional techniques with modern precision tools.",
                "My workshop smells of metal polish and oil. It's home to me.",
                "The brass instruments for the city orchestra? Those are mine!",
                "I'm teaching my daughter the trade. She's already better than I was at her age.",
                "The interplay of light on polished brass creates such warmth!",
                "I source my brass from three different foundries to get the perfect color.",
                "Commissioned pieces tell stories - family crests, commemorative plaques.",
                "The sound brass makes when struck reveals its quality and composition.",
                "I've repaired antique pieces over three centuries old. Historical treasures!",
                "My personal favorite project was the chandelier for the opera house.",
                "The mechanical precision required for working parts is incredibly demanding.",
                "Brass doesn't rust, but it does develop character over time.",
                "I've exhibited my work at the World's Fair. Won a gold medal!",
                "The Art Deco movement is influencing my new designs significantly.",
                "Young artisans need to learn patience. Rushing ruins the work.",
                "I keep a journal sketching new ideas. Currently on volume forty-three!",
                "The guild of brass workers meets monthly to share techniques.",
                "May your journey shine as bright as polished brass, friend!"
            ],
            'Ironside': [
                "Name's Ironside. I work security for the industrial district.",
                "These streets can be dangerous after dark. Steam vents and machinery.",
                "I've stopped three sabotage attempts this year alone. Vigilance is key.",
                "The night watch carries steam-powered lanterns. Essential equipment!",
                "I know every alley and shortcut in this district. Thirty years of patrols.",
                "The factory owners hired me after the great fire of '98. Never again.",
                "I've got a whistle that can be heard for half a mile. Gets attention fast!",
                "The worker disputes get heated sometimes, but we keep things civil.",
                "My armored coat can withstand steam burns and flying sparks.",
                "I coordinate with the fire brigade. They're heroes, every one of them.",
                "The pressure gauges throughout the district report to my monitoring station.",
                "I caught a group trying to steal copper wire last month. Bold as brass!",
                "The automatic alarm systems I installed have saved dozens of lives.",
                "I train new security officers in industrial safety protocols.",
                "My rounds take four hours to complete. Every building gets checked.",
                "The steam-powered siren warns of pressure emergencies. Loud as thunder!",
                "I've got keys to every building in the district. Heavy responsibility.",
                "The dock workers respect the rules. They know I'm fair but firm.",
                "I mediate disputes between shifts sometimes. Keeps the peace.",
                "My grandfather was a constable. I'm carrying on the tradition.",
                "The logbook I maintain has records dating back twenty years.",
                "I've seen this district grow from twelve buildings to over a hundred.",
                "Technology changes but human nature stays the same. Always watchful.",
                "The workers know I'm here to protect them, not boss them around.",
                "Stay alert and watch your step, friend. This district never sleeps!"
            ],
            'Copperfield': [
                "Greetings! I'm Copperfield, electrical engineer and innovator!",
                "Electricity and steam together create incredible possibilities!",
                "I'm developing arc lamps that could light entire streets from one generator.",
                "The future lies in electromagnetic systems integrated with steam power.",
                "My laboratory has equipment that would seem like magic to people just decades ago.",
                "Tesla and Edison both have interesting ideas, but I'm charting my own course.",
                "The copper wiring throughout the city carries messages via telegraph instantly!",
                "I've invented a steam-powered dynamo that generates continuous electricity.",
                "The relationship between voltage, current, and resistance fascinates me daily.",
                "My experiments with wireless transmission show promising results!",
                "The city council approved my proposal for electric street lighting.",
                "I've got batteries that can store energy for days. Revolutionary!",
                "The spark gap transmitter can send signals over fifty miles.",
                "Electromagnetic motors are more efficient than pure mechanical systems.",
                "I'm collaborating with Gearhart on electromagnetically tempered steel.",
                "My biggest breakthrough was the rotating commutator design. Patent pending!",
                "The danger of high voltage keeps me cautious and methodical.",
                "I lecture at the technical institute twice weekly on electrical theory.",
                "The electro-pneumatic systems combine the best of both technologies.",
                "My workshop has enough voltage to power twenty homes simultaneously.",
                "I'm designing an electric tram system to complement the steam rail.",
                "The transformer I invented steps voltage up or down as needed.",
                "Young inventors send me proposals weekly. I try to mentor when I can.",
                "The intersection of disciplines creates the greatest innovations!",
                "May your current be steady and your circuits well-insulated, friend!"
            ],
            'Valvina': [
                "Hello dear! I'm Valvina, chief engineer at the central pumping station.",
                "Managing water pressure for the entire city is quite the responsibility!",
                "The aqueduct system has over two hundred miles of pipes and valves.",
                "I designed the pressure regulation system that prevents pipe bursts.",
                "Clean water is the foundation of public health and prosperity.",
                "The steam-powered pumps can move a million gallons per day!",
                "I started as an apprentice and worked my way up over fifteen years.",
                "The discrimination I faced early on just made me more determined.",
                "Now I supervise a team of forty engineers. We keep the water flowing!",
                "The filtration systems remove contaminants and ensure water quality.",
                "I've installed pressure sensors at key points throughout the network.",
                "My emergency response protocols have prevented several major floods.",
                "The winter freeze prevention systems were my most challenging project.",
                "I teach hydraulic engineering at the polytechnic institute.",
                "The ancient Roman aqueducts inspire my designs. Beautiful and functional!",
                "My daughter is studying to be an engineer too. I'm so proud!",
                "The mathematics of fluid dynamics are elegant and complex.",
                "I've written three technical manuals on water system management.",
                "The integration of steam power and hydraulics opens new possibilities.",
                "Every neighborhood deserves reliable clean water. It's a matter of justice.",
                "The pressure testing protocols I developed are now industry standard.",
                "I consult for cities across the country on water infrastructure.",
                "My pocket calculator is invaluable for on-the-spot flow calculations.",
                "The sound of water flowing smoothly means I've done my job right.",
                "Stay hydrated and keep your pressure balanced, friend!"
            ],
            'Rivetina': [
                "Hey there! I'm Rivetina, airship construction specialist!",
                "I rivet together the frames of flying machines. Dangerous but thrilling work!",
                "The airship yards are where dreams of flight become reality.",
                "I've worked on vessels from small scouts to massive cargo dirigibles.",
                "Being up on the scaffolding hundreds of feet high isn't for everyone!",
                "The sound of riveting echoes across the yards like mechanical thunder.",
                "Every rivet must be perfect. Lives depend on the structural integrity.",
                "I can drive a hundred rivets in an hour with my pneumatic gun.",
                "The aluminum alloys are lighter than steel but just as strong.",
                "I've traveled on every airship I've helped build. Quality assurance!",
                "The view from the top of an airship frame is absolutely breathtaking.",
                "My team assembled the royal flagship in just three months.",
                "The precision required is intense - misaligned rivets weaken the whole structure.",
                "I've got arms like iron from years of wielding the rivet gun.",
                "The dirigible hangars are massive. You could fit a whole block inside!",
                "I trained in the military dockyards before going commercial.",
                "The new gas bags use rubberized fabric that's practically leak-proof.",
                "I've seen the city from above dozens of times. Never gets old!",
                "The engineering calculations for weight distribution are mind-boggling.",
                "My safety harness has saved my life twice. Always double-check it!",
                "The maiden voyage of a new airship fills me with pride every time.",
                "I'm mentoring young women who want to join the construction trades.",
                "The camaraderie among the rivet gangs is like a second family.",
                "Flight represents humanity's greatest ambition made manifest!",
                "Keep your feet on the ground and your dreams in the sky, friend!"
            ],
            'Piston': [
                "Piston's what they call me! I run the engine testing facility.",
                "We push engines to their absolute limits to find weaknesses.",
                "The test stands can simulate years of use in just weeks.",
                "I've seen engines explode from design flaws. That's why testing matters!",
                "The data we collect informs every new engine design in production.",
                "I've got instruments measuring pressure, temperature, vibration, everything.",
                "The sound of an engine at full throttle is magnificent and terrifying!",
                "My team prevented a defective batch from reaching production. Saved lives!",
                "The stress testing procedures I developed are now international standards.",
                "I've worked with engines from tiny clockwork to massive ship propulsion.",
                "The metallurgical analysis reveals stress fractures before they become failures.",
                "I love taking apart engines to understand exactly how they failed.",
                "The engineering margins between success and disaster are surprisingly small.",
                "I've consulted on engine designs for trains, ships, and factories.",
                "My logbooks contain failure analysis data going back twelve years.",
                "The newer composite materials show excellent performance under stress.",
                "I've testified in legal proceedings about engine failures and liability.",
                "Every destroyed engine teaches lessons that save future ones.",
                "The acoustic signatures reveal bearing problems before they cause damage.",
                "I'm developing non-destructive testing methods using electromagnetic induction.",
                "The test facility runs twenty-four hours a day, three shifts.",
                "I've trained quality control inspectors for a dozen manufacturing plants.",
                "Understanding failure modes is just as important as understanding success.",
                "The pursuit of reliability drives everything we do here.",
                "May your engines run smooth and your tests prove successful, friend!"
            ],
            'Sprocket': [
                "Name's Sprocket! I maintain the gear systems for the whole industrial complex.",
                "Gears are simple in concept but devilishly precise in execution.",
                "The gear ratios determine speed, torque, and efficiency of every machine.",
                "I can identify a worn gear by sound alone. Each has a signature noise.",
                "The lubrication systems I designed cut maintenance time in half!",
                "A single damaged tooth can bring an entire production line to a halt.",
                "I've got a collection of over five thousand different gears in my workshop.",
                "The geometric calculations for custom gear cutting are quite complex.",
                "I machined a gear with three hundred teeth once. Took a week!",
                "The planetary gear systems are marvels of compact power transmission.",
                "I inspect every gear delivery personally. Quality cannot be compromised.",
                "The bronze gears in the clocktower will outlast us all. Built for centuries!",
                "I've developed heat treatment procedures that extend gear life dramatically.",
                "The sound of perfectly meshed gears is like a mechanical symphony.",
                "I teach gear theory at the mechanics institute on weekends.",
                "My differential gear design won an award from the engineering society.",
                "The relationship between pitch, pressure angle, and load capacity is crucial.",
                "I've repaired gear systems on everything from pocket watches to factory mills.",
                "The advent of precision machining revolutionized gear manufacturing.",
                "I can calculate gear ratios in my head faster than most can with paper!",
                "My apprentices learn that patience and precision are the keys to good gears.",
                "The gear library contains templates for every standard size and configuration.",
                "I'm working on a self-adjusting gear system that compensates for wear.",
                "Every gear tells a story through its wear patterns and usage marks.",
                "Keep your gears greased and your ratios optimal, friend!"
            ],
            'Boiler': [
                "They call me Boiler because I've been tending steam boilers for twenty years!",
                "Boiler safety is no joke. One mistake can level a building.",
                "I inspect every gauge, every valve, every pressure point daily.",
                "The steam pressure has to stay in the green zone. Always vigilant!",
                "I've prevented boiler explosions three times by catching problems early.",
                "The rumble of a boiler at full pressure is powerful and somewhat frightening.",
                "Water quality affects boiler efficiency and longevity dramatically.",
                "I've got certification from the national boiler safety board. Very rigorous!",
                "The emergency blow-off valves are tested weekly without fail.",
                "I can tell boiler condition by feel, sound, and even smell.",
                "My grandfather died in a boiler explosion. I take this work personally.",
                "The new steel alloys can handle higher pressures safely than ever before.",
                "I train every new boiler operator in proper safety procedures.",
                "The pressure relief systems are the most important safety feature.",
                "I've seen scale buildup reduce efficiency by thirty percent. Maintenance matters!",
                "The boiler insurance inspectors know me by name. I maintain exemplary records.",
                "My emergency shutdown procedures can secure a boiler in under ninety seconds.",
                "The boiler room is my domain. I know every pipe and valve intimately.",
                "I've worked on boilers from five horsepower to five thousand horsepower.",
                "The mathematics of thermodynamics govern everything I do.",
                "I keep spare parts for every critical component on hand at all times.",
                "The boiler operator's union fights for safety standards and fair treatment.",
                "I've written safety pamphlets that are distributed to every facility in the region.",
                "Respect the power of steam. It demands constant attention and care.",
                "Stay safe and keep your pressure within limits, friend!"
            ],
            'Gauge': [
                "Hello! I'm Gauge, precision instrument maker and calibration specialist!",
                "Every pressure gauge, thermometer, and meter passes through my workshop.",
                "Accurate measurements are the foundation of safe industrial operations.",
                "I calibrate instruments against master standards monthly.",
                "A gauge that reads incorrectly is worse than no gauge at all!",
                "I've designed custom instruments for specialized industrial applications.",
                "The precision required is measured in thousandths of an inch.",
                "I use microscopes and precision tools that are themselves calibrated regularly.",
                "The Bourdon tube design revolutionized pressure measurement. Elegant!",
                "I've got reference standards that are traceable to the national bureau.",
                "The quality control testing ensures every instrument meets specifications.",
                "I can spot a counterfeit gauge at a glance. The details give them away.",
                "My reputation for accuracy means engineers trust my instruments with their lives.",
                "The temperature compensation in my designs prevents seasonal drift.",
                "I've invented several specialized gauges that are now industry standard.",
                "The dial faces are hand-painted with markings precise to one degree.",
                "I repair antique instruments, maintaining historical scientific equipment.",
                "The mathematics of measurement and error analysis fascinate me.",
                "I consult on instrumentation design for experimental equipment.",
                "My workshop contains measurement standards worth a small fortune.",
                "The satisfaction of perfect calibration is deeply rewarding.",
                "I teach instrument theory and calibration techniques at the technical school.",
                "Every instrument that leaves my shop comes with certification papers.",
                "Precision instruments enable precision engineering. It's all connected!",
                "May your measurements be accurate and your instruments true, friend!"
            ],
            'Wrenchley': [
                "Wrenchley's the name! I'm the general maintenance supervisor.",
                "If it breaks, leaks, or stops working, my team fixes it!",
                "I've got a tool belt that weighs thirty pounds. Everything I need!",
                "The trick to maintenance is fixing small problems before they become big ones.",
                "I've repaired everything from pocket watches to factory mill drives.",
                "My crew responds to emergency calls twenty-four hours a day.",
                "The preventive maintenance schedules I created cut downtime dramatically.",
                "I can disassemble and reassemble most machines blindfolded by now!",
                "The secret to maintenance is understanding how things are supposed to work.",
                "I've trained apprentices who now run their own maintenance operations.",
                "My collection of specialized tools numbers in the hundreds.",
                "The sound of a malfunctioning machine tells me exactly what's wrong.",
                "I've jury-rigged temporary fixes that held for years!",
                "The maintenance logbooks track every repair, replacement, and adjustment.",
                "I negotiate with suppliers for bulk parts purchases. Saves the company money!",
                "My emergency repair kit can handle ninety percent of common failures.",
                "The satisfaction of getting a dead machine running again never gets old.",
                "I've got scars and calluses from decades of hands-on work.",
                "The newer machines are more complex but also more reliable when maintained properly.",
                "I coordinate with operations to schedule maintenance during downtime.",
                "My team's response time averages under fifteen minutes for urgent calls.",
                "The camaraderie among maintenance workers crosses all industrial trades.",
                "I've improvised solutions using whatever materials were at hand countless times.",
                "Every machine has quirks and personality. You learn them over time.",
                "Keep your tools sharp and your mind sharper, friend!"
            ],
            'Tinker': [
                "Hello! I'm Tinker, inventor of small mechanisms and gadgets!",
                "I work on the tiny intricate devices that make modern life convenient.",
                "My workshop is filled with clockwork mechanisms and miniature machines.",
                "I've patented seventeen different devices from door locks to computing machines!",
                "The miniaturization challenges are immense but so rewarding to solve.",
                "I've created a mechanical calculator that fits in your pocket!",
                "The precision required for small gears and springs is extraordinary.",
                "I use watchmaker's tools and jeweler's loupes for my finest work.",
                "My automatic door closer design is used throughout the city now.",
                "I've invented timing mechanisms for photography, cooking, and industrial processes.",
                "The kinetic energy storage in spring mechanisms is quite remarkable.",
                "I collaborate with clockmakers on complicated timepiece movements.",
                "My music box designs incorporate programmable drum mechanisms.",
                "The mechanical encryption device I invented is used for secure communications!",
                "I've built prosthetic hands with articulated fingers. Life-changing for patients!",
                "The puzzle boxes I create as gifts are famous among friends and family.",
                "I source materials from around the world - Swiss springs, Japanese steel.",
                "My designs emphasize reliability and serviceability. Things should be repairable!",
                "I've created adaptive devices for people with disabilities. Deeply meaningful work.",
                "The intersection of art and engineering in small mechanisms is beautiful.",
                "I teach courses on micromechanics and precision manufacturing.",
                "My patent portfolio generates licensing revenue that funds new research.",
                "I've been consulted on miniature components for medical instruments.",
                "Every tiny mechanism is a puzzle to solve and a creation to perfect.",
                "May your mechanisms work smoothly and your inventions inspire others, friend!"
            ],
            'Steamson': [
                "Steamson here! I operate the central steam distribution hub!",
                "The city's entire steam network flows through my control station.",
                "I monitor pressure levels across two hundred distribution points constantly.",
                "The control panel has over a thousand valves, gauges, and switches!",
                "I can redirect steam flow to respond to changing demand in real-time.",
                "The morning rush when factories start up is intense. All hands on deck!",
                "I've managed steam distribution for fifteen years without a major incident.",
                "The backup systems ensure continuous supply even during equipment failures.",
                "I coordinate with power plant operators on generation levels.",
                "The steam network map covers an entire wall of my control room.",
                "I've optimized routing to reduce heat loss by twenty percent!",
                "The emergency protocols can isolate sections to contain leaks or breaks.",
                "I train operators on the complexity of network management and safety.",
                "The pressure balancing between high and low demand areas requires constant attention.",
                "I've installed remote monitoring that alerts me to problems immediately.",
                "The economic impact of reliable steam distribution is enormous!",
                "I work closely with maintenance teams to schedule repairs during low demand.",
                "The steam network expansion plans will double capacity over five years.",
                "I've written operational manuals that are used by other cities now.",
                "The satisfaction of keeping the city running smoothly is immense.",
                "I've consulted on steam network design for three other cities.",
                "The automation systems I've implemented reduce manual intervention significantly.",
                "My shift logs document every adjustment and response decision.",
                "The steam distribution hub is the beating heart of our industrial civilization!",
                "Keep your systems balanced and your backups ready, friend!"
            ],
            'Brassmith': [
                "I'm Brassmith, owner of the largest brass foundry in the region!",
                "We pour molten brass into molds to create thousands of components daily.",
                "The foundry employs over three hundred skilled workers across three shifts.",
                "The heat from the furnaces is intense. We go through tons of coal weekly!",
                "I started as a floor worker and bought the foundry twenty years later.",
                "The brass alloy recipes are closely guarded trade secrets.",
                "We cast everything from tiny fittings to massive valve bodies.",
                "The quality control process ensures every casting meets specifications.",
                "I've invested in modern casting equipment that's more efficient and safer.",
                "The workers' safety is my top priority. We have an excellent safety record!",
                "I negotiate brass ingot purchases directly with the copper and zinc producers.",
                "The foundry operates on thin margins but steady volume.",
                "I've established apprenticeship programs to develop the next generation.",
                "The contracts with manufacturers provide stable long-term business.",
                "I'm active in the brass founders association, advocating for fair practices.",
                "The environmental considerations of foundry operations are increasingly important.",
                "I've installed filtering systems to reduce smoke and particulate emissions.",
                "The foundry has been in continuous operation for seventy-five years!",
                "I know most of my workers by name and their families too.",
                "The profit-sharing plan I instituted boosts morale and productivity.",
                "I've weathered economic downturns through careful financial management.",
                "The expansion project will add two new furnaces next year.",
                "I take pride in contributing to the city's industrial prosperity.",
                "A strong business builds a strong community. That's my philosophy!",
                "May your ventures be profitable and your work meaningful, friend!"
            ],
            'Coalburn': [
                "They call me Coalburn - I manage the fuel depot and coal yards!",
                "Coal is the lifeblood of our steam-powered civilization!",
                "We receive trainloads of coal daily from the mountain mines.",
                "The different grades of coal serve different purposes and applications.",
                "I can identify coal quality by its color, weight, and how it breaks.",
                "The storage yards hold enough coal to power the city for two months!",
                "I coordinate deliveries to factories, power plants, and residential customers.",
                "The coal dust is a constant battle - it gets everywhere!",
                "I've negotiated contracts with four different mining companies for best prices.",
                "The weighing and accounting systems ensure accurate billing and inventory.",
                "I employ teamsters who deliver coal throughout the city daily.",
                "The anthracite coal burns cleaner and hotter than bituminous.",
                "I've seen the coal industry evolve dramatically over my thirty years.",
                "The environmental concerns about smoke are driving demand for cleaner fuels.",
                "I'm investigating coke production as a cleaner alternative fuel source.",
                "The coal yards operate year-round, but winter demand spikes dramatically.",
                "I maintain emergency reserves for the city's critical infrastructure.",
                "The logistics of coal distribution are complex and time-sensitive.",
                "I've weathered mining strikes by maintaining strategic stockpiles.",
                "The coal workers union and I have a respectful working relationship.",
                "I've diversified into fuel oil and gas as alternatives to coal.",
                "The financial side requires careful management of credit and collections.",
                "I take samples from every delivery to verify quality standards.",
                "The future may bring new fuels, but coal remains king for now!",
                "May your fires burn bright and your fuel be plentiful, friend!"
            ],
            'Gearston': [
                "Gearston at your service! I'm the city's premier machinist!",
                "I manufacture custom parts that can't be bought off the shelf.",
                "The machine shop contains lathes, mills, shapers, and grinders.",
                "Precision tolerances of a thousandth of an inch are routine for me.",
                "I've made replacement parts for machines that haven't been manufactured in decades!",
                "The blueprints I work from are sometimes hand-sketched on napkins!",
                "I can reverse-engineer a part from a broken sample.",
                "The metal cutting speeds and feeds must be precise for quality results.",
                "I've trained dozens of machinists who now work throughout the region.",
                "The smell of cutting oil and metal chips is the perfume of precision!",
                "I've made parts for clocktowers, engines, printing presses, you name it!",
                "The investment in quality tools pays for itself in accurate work.",
                "I can read blueprints in my sleep after forty years of this work.",
                "The satisfaction of a perfectly fitted part is deeply rewarding.",
                "I've consulted on designs to make parts more manufacturable.",
                "The newer automatic screw machines can produce parts much faster!",
                "I maintain tolerances that some say are unnecessarily tight. I disagree!",
                "The shop runs efficiently because every tool has its place and purpose.",
                "I've made experimental parts for inventors testing new ideas.",
                "The material selection affects machining techniques significantly.",
                "I've salvaged projects others said were impossible to manufacture.",
                "The machinist's handbook is my bible - worn and annotated extensively.",
                "I take pride in being the problem-solver others call when stuck.",
                "Every part that leaves my shop has my reputation stamped on it!",
                "May your fits be tight and your surfaces smooth, friend!"
            ],
            'Mechanique': [
                "Bonjour! I'm Mechanique, automaton designer from the Continent!",
                "I create mechanical beings that can perform tasks autonomously!",
                "The clockwork mechanisms that drive my automata are incredibly complex.",
                "I've built mechanical servants that can pour tea without spilling a drop!",
                "The programming is done through cams, pins, and rotating drums.",
                "I've created an automaton orchestra that plays actual musical instruments!",
                "The artistry in automaton design combines engineering and sculpture.",
                "I use the finest Swiss movements and French metalwork techniques.",
                "My automatons have been displayed in exhibitions across Europe!",
                "The wealthy commission custom pieces as status symbols and entertainments.",
                "I've built a mechanical bird that flies in realistic patterns!",
                "The challenge is creating fluid, lifelike motion from rigid parts.",
                "I've studied anatomy to replicate realistic movement in my creations.",
                "My workshop contains unfinished projects that may take years to complete.",
                "The most complex automaton I've built has over two thousand parts!",
                "I've collaborated with watchmakers on miniature mechanism designs.",
                "The steam-powered automatons I'm developing will be truly revolutionary!",
                "I dream of creating an automaton capable of playing chess strategically.",
                "The philosophical questions about mechanical life fascinate me deeply.",
                "I've repaired antique automatons from the Renaissance era. Priceless artifacts!",
                "My designs push the boundaries of what's possible with purely mechanical systems.",
                "I lecture on biomechanics and kinematic design at the university.",
                "The intersection of art, engineering, and philosophy drives my work.",
                "Each automaton is a meditation on the nature of life and motion itself.",
                "May your movements be graceful and your mechanisms alive with purpose, friend!"
            ],
            'Boltsworth': [
                "Boltsworth's my name! I manufacture fasteners - bolts, nuts, screws, rivets!",
                "Every machine, building, and vehicle is held together by fasteners!",
                "The threading standards I helped establish ensure interchangeability.",
                "I produce millions of fasteners annually across hundreds of specifications.",
                "The heat treatment process determines the strength of each fastener.",
                "I've developed specialty fasteners for high-vibration applications.",
                "The quality control involves testing tensile strength and thread accuracy.",
                "I supply fasteners to shipyards, railroads, factories, and construction projects.",
                "The inventory system tracks over five thousand different SKUs!",
                "I've automated much of the production with specialized screw machines.",
                "The corrosion resistance of galvanized fasteners extends their lifespan dramatically.",
                "I work with material scientists on new alloys for extreme applications.",
                "The threading dies must be replaced frequently to maintain accuracy.",
                "I've consulted on fastener failures to improve designs and materials.",
                "The economics of high-volume, low-margin manufacturing are challenging!",
                "I've established a distribution network spanning three countries.",
                "The technical specifications for aerospace applications are incredibly demanding.",
                "I employ metallurgists who ensure consistent material properties.",
                "The fastener catalog I publish is used as a reference throughout the industry.",
                "I've pioneered self-locking nut designs that resist vibration loosening.",
                "The relationship between thread pitch, diameter, and load capacity is crucial.",
                "I take pride in the reliability of my products in critical applications.",
                "The fastener industry is underappreciated but absolutely essential!",
                "Every project depends on the humble fastener holding things together.",
                "May your connections be strong and your threads true, friend!"
            ]
        };
    }

    tryInteract(playerPos, forward) {
        const npc = this.npcManager.getNPCInView(playerPos, forward, 15);
        if (npc && !this.currentNPC) {
            this.startDialog(npc);
        }
    }

    startDialog(npc) {
        this.currentNPC = npc;
        npc.dialogIndex = 0;
        this.showDialog();
    }

    showDialog() {
        if (!this.currentNPC) return;

        const lines = this.dialogs[this.currentNPC.name] || ['Hello there!'];
        const line = lines[this.currentNPC.dialogIndex];

        this.npcNameEl.textContent = this.currentNPC.name;
        this.dialogTextEl.textContent = line;
        this.dialogBox.classList.add('active');

        // Voice synthesis
        if (this.synth) {
            this.synth.cancel();
            const utterance = new SpeechSynthesisUtterance(line);
            utterance.rate = 0.9;
            utterance.pitch = 1.0;
            this.synth.speak(utterance);
        }
    }

    continueDialog() {
        if (!this.currentNPC) return;

        const lines = this.dialogs[this.currentNPC.name] || ['Hello there!'];
        this.currentNPC.dialogIndex++;

        if (this.currentNPC.dialogIndex >= lines.length) {
            this.endDialog();
        } else {
            this.showDialog();
        }
    }

    endDialog() {
        this.dialogBox.classList.remove('active');
        if (this.synth) this.synth.cancel();
        this.currentNPC = null;
    }

    isDialogActive() {
        return this.currentNPC !== null;
    }

    update(playerPos, npcManager) {
        // Auto-close if player walks away
        if (this.currentNPC) {
            const dist = this.currentNPC.position.distanceTo(playerPos);
            if (dist > 20) this.endDialog();
        }
    }
}
